import Link from 'next/link';
import { notFound } from 'next/navigation';
import { SiteShell } from '@/components/site-shell';
import { pageMetadata } from '@/lib/seo';
const pages:Record<string,{title:string;sections:{heading:string;text:string}[]}>= {
 'lien-he':{title:'Hỗ trợ cuộc vui',sections:[{heading:'Đã chuyển khoản nhưng chưa mở khóa?',text:'Quay về trang thanh toán và chọn Kiểm tra lại. Giữ mã đơn, thời điểm chuyển, số tiền và mã giao dịch ngân hàng. Đừng chuyển thêm tiền khi đơn đầu tiên chưa được kiểm tra.'},{heading:'Mất quyền chơi trên thiết bị mới?',text:'Vào Bộ đã mua và nhập mã khôi phục được cấp sau thanh toán. Không gửi mã này công khai vì người có mã có thể mở lại bộ của bạn.'},{heading:'Kênh hỗ trợ',text:process.env.NEXT_PUBLIC_SUPPORT_EMAIL?`Liên hệ: ${process.env.NEXT_PUBLIC_SUPPORT_EMAIL}. Gửi mã đơn và mô tả sự cố; không gửi mật khẩu hoặc OTP ngân hàng.`:'Bản phát triển chưa thiết lập kênh hỗ trợ và chưa sẵn sàng nhận thanh toán thật. Chủ ứng dụng cần bổ sung thông tin liên hệ trước khi mở bán.'}]},
 'chinh-sach-thanh-toan':{title:'Thông tin thanh toán',sections:[{heading:'Mua một bộ, chơi nhiều lần',text:'Mỗi lần mua mở khóa một bộ premium và các cập nhật của cùng bộ. Quyền chơi không có ngày hết hạn trong thời gian dịch vụ hoạt động. Bộ mới khác không tự được bao gồm. Giá được hiển thị và xác nhận trước khi tạo đơn.'},{heading:'Xác nhận chuyển khoản',text:'Chuyển đúng số tiền và nội dung trên đơn. Hệ thống chỉ mở khóa sau khi ghi nhận thanh toán qua SePay. Nếu đã chuyển nhưng chưa mở khóa, hãy kiểm tra lại trạng thái; không chuyển lại ngay.'},{heading:'Giữ mã khôi phục',text:'Sau khi mua, lưu mã khôi phục để dùng khi đổi trình duyệt hoặc thiết bị. Không cần tạo tài khoản. Mã khôi phục là quyền truy cập bộ đã mua, vì vậy chỉ chia sẻ khi bạn chủ động muốn làm điều đó.'},{heading:'Bản chạy thử',text:'Các bộ hiện tại có ít câu minh họa để thử trải nghiệm. Thanh toán chỉ hoạt động sau khi chủ ứng dụng cấu hình ngân hàng, SePay, dữ liệu sản phẩm và kênh hỗ trợ. Không phát sinh thanh toán khi hệ thống chưa sẵn sàng.'}]},
 'quyen-rieng-tu':{title:'Quyền riêng tư',sections:[{heading:'Tên nhóm và câu hỏi AI',text:'Nhóm chơi thường và tên hoặc biệt danh được lưu trên trình duyệt. Khi bạn bấm tạo bộ AI, tên nhóm, thành viên và mood được gửi đến Vercel AI Gateway và nhà cung cấp mô hình để tạo nội dung; đầu vào và bộ câu hỏi được lưu riêng trong database theo phiên khách. Link bộ riêng không cấp quyền cho thiết bị khác. Xóa dữ liệu trình duyệt không tự xóa bản đã lưu trên server. Không thu câu trả lời của thành viên.'},{heading:'Không thu câu trả lời',text:'Ứng dụng không yêu cầu bạn nhập hoặc gửi câu trả lời Thật hay Thách. Tiến độ ván và nội dung đã tải được lưu trên trình duyệt của bạn.'},{heading:'Dữ liệu khi mua bộ',text:'Khi thanh toán được kích hoạt, hệ thống dùng cookie khách để liên kết đơn hàng và lưu trạng thái giao dịch, số tiền, mã giao dịch và quyền mua. Không yêu cầu tài khoản người chơi.'},{heading:'Dữ liệu trên thiết bị',text:'Xóa dữ liệu website sẽ xóa tiến độ và bộ offline. Quyền mua có thể khôi phục bằng mã đã lưu. Chế độ duyệt riêng tư có thể không giữ dữ liệu khi đóng trình duyệt.'},{heading:'Thống kê',text:'Bản này chưa gắn dịch vụ theo dõi quảng cáo hay công cụ analytics bên thứ ba. Không gửi mã khôi phục hoặc câu trả lời của người chơi tới hệ thống thống kê.'}]},
};
export const dynamicParams=false;
export function generateStaticParams(){return Object.keys(pages).map(info=>({info}));}
export async function generateMetadata({params}:{params:Promise<{info:string}>}){const info=(await params).info;const p=pages[info];return p?pageMetadata(p.title,p.sections[0].text,`/vi/${info}`):{};}
export default async function Info({params}:{params:Promise<{info:string}>}){const p=pages[(await params).info];if(!p)notFound();return <SiteShell><main id="main" className="page-width article-page"><Link className="back-link" href="/vi">← Trang chủ</Link><h1>{p.title}</h1>{p.sections.map(s=><section key={s.heading}><h2>{s.heading}</h2><p>{s.text}</p></section>)}</main></SiteShell>;}
