import Link from 'next/link';
import { ArrowRight, Zap, Download, Heart } from 'lucide-react';
import { SiteShell } from '@/components/site-shell';
import { PackLibrary } from '@/components/pack-library';
import { StructuredData } from '@/components/structured-data';
import { AiInvitation } from '@/components/ai-invitation';
import { getCategories, getPacks } from '@/lib/content';
import { pageMetadata, siteUrl } from '@/lib/seo';
export const metadata = pageMetadata('Thật hay Thách — Chọn một câu, gần nhau hơn','Bộ câu hỏi Thật hay Thách cho bạn bè và cặp đôi. Chơi miễn phí, không cần đăng nhập, ngay trên điện thoại.','/vi');
export default function Home() {
 const packs=getPacks(); const categories=getCategories();
 return <SiteShell><main id="main" className="page-width home"><section className="intro"><div className="intro-copy"><span className="eyebrow"><span className="tiny-spark">✦</span> CUỘC VUI BẮT ĐẦU TỪ MỘT CÂU HỎI</span><h1>Bớt ngại ngùng.<br/><span>Thêm gần nhau.</span></h1><p>Chọn Thật để hiểu nhau hơn, chọn Thách để cùng bật cười.<br className="desktop-break"/> Một chiếc điện thoại là đủ cho cả cuộc vui.</p><div className="intro-actions"><a className="button button-primary" href="/vi/choi/ban-be-khoi-dong">Chơi ngay miễn phí<ArrowRight size={19}/></a><a className="group-start" href="/vi/choi/ban-be-khoi-dong?group=1">Tạo nhóm & chơi →</a></div><div className="intro-notes"><span><Zap size={14}/>Không cần tài khoản</span><span><Download size={14}/>Chơi cả khi offline</span></div></div><div className="intro-cards" aria-hidden="true"><div className="mini-card mini-truth"><span>💭 THẬT</span><p>Ấn tượng đầu tiên<br/>của bạn về mình?</p><small>THÀNH THẬT MỘT CHÚT</small></div><div className="mini-card mini-dare"><span>💖 THÁCH</span><p>Thử làm cả nhóm<br/>cười trong 10 giây.</p><small>CAN ĐẢM MỘT CHÚT</small></div><span className="floating-spark">✦</span></div></section><AiInvitation/><PackLibrary packs={packs} categories={categories}/><section className="how-strip"><div className="how-heart"><Heart size={22}/></div><div><h2>Không cần giỏi chơi. Chỉ cần là chính mình.</h2><p>Chọn một bộ, chuyền điện thoại và lần lượt chọn Thật hoặc Thách. Luôn có thể bỏ qua khi bạn không thoải mái.</p></div><Link href="/vi/cach-choi">Xem cách chơi<ArrowRight size={17}/></Link></section><section className="home-faq"><h2>Một chút trước khi chơi</h2><details><summary>Thật hay Thách chơi như thế nào?</summary><p>Mỗi người lần lượt chọn Thật để trả lời một câu hỏi hoặc Thách để thực hiện thử thách. Mọi người có thể bỏ qua bất cứ lúc nào. Không có điểm số hay người thắng cuộc.</p></details><details><summary>Có cần tải ứng dụng hoặc đăng ký không?</summary><p>Không. Bạn chơi ngay trong trình duyệt. Có thể thêm vào màn hình chính và lưu bộ câu hỏi để chơi khi không có mạng.</p></details><details><summary>Bộ premium khác gì bộ miễn phí?</summary><p>Bộ miễn phí mở toàn bộ câu hỏi. Mỗi bộ premium có 8 câu chơi thử; thanh toán một lần để mở phần còn lại và chơi lại không giới hạn. Giá được xác nhận trước khi thanh toán.</p></details></section></main><StructuredData data={{'@context':'https://schema.org','@type':'WebSite',name:'Thật hay Thách',url:siteUrl+'/vi',inLanguage:'vi'}}/></SiteShell>;
}
